
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslated-messages-file.txt
# explicitely generate the file to avoid: couldn't resolve the package 'flutter_gen'
synthetic-package: false
output-dir: lib/l10n/gen/

# Enable translation (via DeepL)
translate: false              
# Auto-run flutter gen-l10n after extraction              
generate: true       
# Key prefix for translations             
key-prefix: AppLocalizations.of(context).  
# Generate key name
# "ask" = prompt with pre-filled text, true = infer from text, false = prompt manually  
auto-name-key: false       
# Language to use for key name generation                 
key-name-language: en       
# Import line to insert if needed                
import-line: import 'package:coinio_app/l10n/gen/app_localizations.dart'; 
