name: coinio_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  shake: ^3.0.0
  fuzzywuzzy: ^1.2.0
  spoiler_widget: ^1.0.12
  drift: ^2.27.0
  path_provider: ^2.1.5
  path: ^1.9.1
  get_it: ^8.0.3
  # My package with AnimatedPieChart
  fl_chart: ^1.0.0
  intl: ^0.20.2
  my_first_package:
    git:
      url: https://github.com/pablobagdal/my_first_package.git
      ref: main
  flutter_dotenv: ^5.2.1
  worker_manager: ^7.2.6
  dio: ^5.8.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  icons_launcher: ^3.0.1
  drift_dev: ^2.27.0
  flutter_native_splash: ^2.4.6
  logger: ^2.6.0




flutter:
  uses-material-design: true
  fonts:
    - family: MyIcons
      fonts:
        - asset: assets/fonts/MyIcons.ttf 
  assets:
    - .env

# Run the following commands to set up the icon launcher:
# 1) flutter pub get
# 2) dart run icons_launcher:create
icons_launcher:
  image_path: 'assets/logo.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true

# Run the following commands to set up the splash screen:
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
  # light mode support
  # color: "#2AE880"
  color: "#e1f5fe"
  #background_image: "assets/background.png"

  # image: assets/logo.png
  image: assets/logo_lockup_flutter_vertical.png
  #branding: assets/dart.png
  #branding_mode: bottom
  # branding_bottom_padding: 24

  # dark mode support
  # color_dark: "#2AE880"
  color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  image_dark: assets/logo_lockup_flutter_vertical_wht.png
  #branding_dark: assets/dart_dark.png

  android_12:
    image: assets/android12splash.png
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.  To fit a 1152x1152 image within a circle with a 768 diameter, simply 
    # ensure that the most important design elements of your image are placed within a circular area
    # with a 768 diameter at the center of the 1152x1152 canvas.
    #image: assets/android12splash.png

    # Splash screen background color.
    # color: "#2AE880"
    color: "#42a5f5"
    # App icon background color.
    #icon_background_color: "#111111"
    icon_background_color: "#eeeeee"
    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    #image_dark: assets/android12splash-invert.png
    color_dark: "#2AE880"
    #icon_background_color_dark: "#eeeeee"

  android: true
  ios: true
  web: false